# Generated by Django 5.0.1 on 2024-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='graph2',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 2'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph3',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 3'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph4',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 4'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph5',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 5'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph6',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 6'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph7',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 7'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph8',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 8'),
        ),
        migrations.AddField(
            model_name='skills',
            name='graph9',
            field=models.ImageField(default=None, upload_to='skills', verbose_name='График 9'),
        ),
    ]
