# Generated by Django 5.0.1 on 2024-01-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_skills_graph2_alter_skills_graph3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='graph2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph5',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph6',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph7',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph8',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='graph9',
        ),
    ]
